import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { IndianRupee, Zap, Sun, Info, TrendingDown, Leaf, Calendar, ArrowRight, CheckCircle2, Sparkles } from 'lucide-react';

const Resources = () => {
  // Calculator State
  const [monthlyUnits, setMonthlyUnits] = useState(300);
  const [showDetails, setShowDetails] = useState(false);
  const [electricityRate, setElectricityRate] = useState(8);

  // Solar System Data (based on user requirements)
  const solarSystems = [
    { capacity: 1.1, cost: 70000, productionMin: 150, productionMax: 150, subsidy: 18000, panelCount: 3 },
    { capacity: 2, cost: 130000, productionMin: 250, productionMax: 300, subsidy: 30000, panelCount: 5 },
    { capacity: 3, cost: 180000, productionMin: 450, productionMax: 500, subsidy: 45000, panelCount: 8 },
    { capacity: 5, cost: 250000, productionMin: 750, productionMax: 800, subsidy: 78000, panelCount: 13 },
    { capacity: 10, cost: 360000, productionMin: 1400, productionMax: 1600, subsidy: 78000, panelCount: 26 }
  ];

  // Constants
  const AREA_PER_KW = 100; // sq ft per kW
  const CO2_PER_UNIT = 0.82; // kg CO2 per unit
  const TREES_PER_TON_CO2 = 50; // trees needed to offset 1 ton CO2 per year
  const ANNUAL_TARIFF_INCREASE = 0.05; // 5% annual increase in electricity rates

  // Find recommended system based on monthly consumption
  const getRecommendedSystem = () => {
    const targetProduction = monthlyUnits * 0.85; // Target 85% coverage
    
    for (let i = 0; i < solarSystems.length; i++) {
      if (solarSystems[i].productionMin >= targetProduction) {
        return solarSystems[i];
      }
    }
    return solarSystems[solarSystems.length - 1];
  };

  const recommendedSystem = getRecommendedSystem();
  const avgProduction = (recommendedSystem.productionMin + recommendedSystem.productionMax) / 2;
  
  // Financial Calculations
  const currentMonthlyBill = monthlyUnits * electricityRate;
  const solarProduction = Math.min(monthlyUnits, avgProduction);
  const remainingUnits = Math.max(0, monthlyUnits - avgProduction);
  const newMonthlyBill = remainingUnits * electricityRate;
  const monthlySavings = currentMonthlyBill - newMonthlyBill;
  const annualSavings = monthlySavings * 12;
  const systemCostAfterSubsidy = recommendedSystem.cost - recommendedSystem.subsidy;
  const paybackYears = (systemCostAfterSubsidy / annualSavings).toFixed(1);
  const paybackMonths = Math.ceil((systemCostAfterSubsidy / annualSavings) * 12);
  
  // 25-year projections with tariff increase
  const calculate25YearSavings = () => {
    let totalSavings = 0;
    let currentRate = electricityRate;
    for (let year = 1; year <= 25; year++) {
      const yearSavings = solarProduction * currentRate * 12;
      totalSavings += yearSavings;
      currentRate *= (1 + ANNUAL_TARIFF_INCREASE);
    }
    return totalSavings;
  };
  
  const lifetimeSavings = calculate25YearSavings();
  const roi = ((lifetimeSavings - recommendedSystem.cost) / recommendedSystem.cost * 100).toFixed(0);
  
  // Environmental Impact
  const annualCO2Saved = (solarProduction * 12 * CO2_PER_UNIT) / 1000; // in tons
  const lifetimeCO2Saved = annualCO2Saved * 25;
  const treesEquivalent = Math.round(lifetimeCO2Saved * TREES_PER_TON_CO2);
  
  // Coverage and other metrics
  const areaNeeded = Math.ceil(recommendedSystem.capacity * AREA_PER_KW);
  const coveragePercent = Math.min(100, Math.round((avgProduction / monthlyUnits) * 100));
  const energyIndependence = Math.min(100, Math.round((solarProduction / monthlyUnits) * 100));

  const faqs = [
    {
      q: "Is my house suitable for solar panels?",
      a: "Most houses in Jaipur with a clear rooftop (unshaded by trees or buildings) are suitable. We conduct a free site audit to check orientation and structural integrity."
    },
    {
      q: "How much government subsidy can I get in Rajasthan?",
      a: "The Central Government provides subsidies for residential rooftops. Typically, it ranges from ₹18,000 to ₹78,000 depending on the system capacity (as per latest PM Surya Ghar Yojana)."
    },
    {
      q: "What is Net Metering?",
      a: "Net metering allows you to export excess electricity generated by your solar system back to the grid. Your bill will only reflect the 'net' consumption (Import - Export)."
    },
    {
      q: "How long do solar panels last?",
      a: "Most high-quality solar panels come with a 25-year performance warranty and can last over 30 years with proper maintenance."
    },
    {
      q: "Does solar work during the rainy season or at night?",
      a: "Solar panels generate power from sunlight, so they don't produce electricity at night. During the rainy season, they still generate power from diffused light, though at a lower efficiency."
    }
  ];

  return (
    <div className="py-20 bg-muted/20">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-start">
          
          {/* Solar Calculator */}
          <section className="space-y-8">
            <div className="space-y-4">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 rounded-full">
                <Sparkles className="w-4 h-4 text-primary" />
                <span className="text-sm font-semibold text-primary">Advanced Calculator</span>
              </div>
              <h2 className="text-3xl md:text-4xl font-black tracking-tight">Solar Savings Calculator</h2>
              <p className="text-muted-foreground text-lg">
                Get a comprehensive analysis with real-time calculations, environmental impact, and financial projections.
              </p>
            </div>

            {/* Quick Summary Dashboard */}
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4">
              <Card className="border-2 border-primary/20 bg-primary/5">
                <CardContent className="pt-4 md:pt-6 text-center space-y-1 md:space-y-2">
                  <div className="text-2xl md:text-3xl font-black text-primary">{recommendedSystem.capacity} kW</div>
                  <div className="text-xs text-muted-foreground font-medium">Recommended Size</div>
                </CardContent>
              </Card>
              
              <Card className="border-2 border-secondary/20 bg-secondary/5">
                <CardContent className="pt-4 md:pt-6 text-center space-y-1 md:space-y-2">
                  <div className="text-2xl md:text-3xl font-black text-secondary">₹{Math.round(monthlySavings / 1000)}K</div>
                  <div className="text-xs text-muted-foreground font-medium">Monthly Savings</div>
                </CardContent>
              </Card>
              
              <Card className="border-2 border-accent/20 bg-accent/5">
                <CardContent className="pt-4 md:pt-6 text-center space-y-1 md:space-y-2">
                  <div className="text-2xl md:text-3xl font-black text-accent">{paybackYears} Yrs</div>
                  <div className="text-xs text-muted-foreground font-medium">Payback Period</div>
                </CardContent>
              </Card>
              
              <Card className="border-2 border-primary/20 bg-primary/5">
                <CardContent className="pt-4 md:pt-6 text-center space-y-1 md:space-y-2">
                  <div className="text-2xl md:text-3xl font-black text-primary">{roi}%</div>
                  <div className="text-xs text-muted-foreground font-medium">25-Year ROI</div>
                </CardContent>
              </Card>
            </div>

            <Card className="border-none shadow-xl bg-background">
              <CardContent className="pt-4 md:pt-6 space-y-6 md:space-y-8">
                {/* Input Section */}
                <div className="space-y-4 md:space-y-6">
                  <div className="space-y-3 md:space-y-4">
                    <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                      <Label className="text-sm md:text-base font-semibold">Monthly Electricity Consumption</Label>
                      <div className="text-right">
                        <div className="text-xl md:text-2xl font-black text-primary">{monthlyUnits} units</div>
                        <div className="text-xs md:text-sm text-muted-foreground">≈ ₹{currentMonthlyBill.toLocaleString('en-IN')}/month</div>
                      </div>
                    </div>
                    <Slider 
                      value={[monthlyUnits]} 
                      min={100} 
                      max={2000} 
                      step={50}
                      onValueChange={(val) => setMonthlyUnits(val[0])}
                      className="cursor-pointer"
                    />
                    <div className="flex justify-between text-xs text-muted-foreground">
                      <span>100 units</span>
                      <span>2,000 units</span>
                    </div>
                  </div>

                  <div className="space-y-3 md:space-y-4">
                    <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                      <Label className="text-sm md:text-base font-semibold">Electricity Rate (per unit)</Label>
                      <div className="text-lg md:text-xl font-bold text-foreground">₹{electricityRate}</div>
                    </div>
                    <Slider 
                      value={[electricityRate]} 
                      min={5} 
                      max={12} 
                      step={0.5}
                      onValueChange={(val) => setElectricityRate(val[0])}
                      className="cursor-pointer"
                    />
                    <div className="flex justify-between text-xs text-muted-foreground">
                      <span>₹5/unit</span>
                      <span>₹12/unit</span>
                    </div>
                  </div>
                </div>

                {/* Before/After Comparison */}
                <div className="space-y-3 md:space-y-4">
                  <h4 className="font-bold text-base md:text-lg flex items-center gap-2">
                    <TrendingDown className="w-4 h-4 md:w-5 md:h-5 text-accent" />
                    Bill Comparison
                  </h4>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 md:gap-4">
                    <div className="p-4 md:p-6 bg-destructive/10 border-2 border-destructive/20 rounded-xl space-y-2 md:space-y-3">
                      <div className="text-xs md:text-sm text-muted-foreground font-medium">WITHOUT SOLAR</div>
                      <div className="text-2xl md:text-4xl font-black text-destructive">₹{currentMonthlyBill.toLocaleString('en-IN')}</div>
                      <div className="text-xs md:text-sm text-muted-foreground">per month</div>
                      <div className="pt-2 border-t border-destructive/20">
                        <div className="text-xs text-muted-foreground">Annual Cost</div>
                        <div className="text-lg md:text-xl font-bold text-destructive">₹{(currentMonthlyBill * 12).toLocaleString('en-IN')}</div>
                      </div>
                    </div>
                    
                    <div className="p-4 md:p-6 bg-accent/10 border-2 border-accent/20 rounded-xl space-y-2 md:space-y-3 relative overflow-hidden">
                      <div className="absolute top-2 right-2">
                        <span className="px-2 md:px-3 py-1 bg-accent text-accent-foreground text-xs font-bold rounded-full">
                          WITH SOLAR
                        </span>
                      </div>
                      <div className="text-xs md:text-sm text-muted-foreground font-medium">NEW BILL</div>
                      <div className="text-2xl md:text-4xl font-black text-accent">₹{newMonthlyBill.toLocaleString('en-IN')}</div>
                      <div className="text-xs md:text-sm text-accent font-semibold">Save ₹{monthlySavings.toLocaleString('en-IN')}/month</div>
                      <div className="pt-2 border-t border-accent/20">
                        <div className="text-xs text-muted-foreground">Annual Savings</div>
                        <div className="text-lg md:text-xl font-bold text-accent">₹{annualSavings.toLocaleString('en-IN')}</div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Recommended System Card */}
                <div className="bg-gradient-to-br from-primary/10 via-primary/5 to-transparent border-2 border-primary rounded-2xl p-4 md:p-6 space-y-4 md:space-y-6">
                  <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                    <div className="flex-1">
                      <div className="text-xs md:text-sm text-primary font-bold mb-2 flex items-center gap-2">
                        <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4" />
                        RECOMMENDED SYSTEM
                      </div>
                      <div className="text-2xl md:text-4xl font-black text-foreground mb-1">{recommendedSystem.capacity} kW Solar System</div>
                      <div className="text-xs md:text-sm text-muted-foreground">{recommendedSystem.panelCount} Solar Panels • {areaNeeded} sq ft required</div>
                    </div>
                    <div className="w-16 h-16 md:w-20 md:h-20 bg-primary rounded-2xl flex items-center justify-center shadow-lg shrink-0">
                      <Sun className="w-8 h-8 md:w-10 md:h-10 text-primary-foreground" />
                    </div>
                  </div>
                  
                  <div className="space-y-3 md:space-y-4">
                    <div>
                      <div className="flex justify-between items-center mb-2">
                        <span className="text-xs md:text-sm text-muted-foreground font-medium">Energy Coverage</span>
                        <span className="text-base md:text-lg font-bold text-accent">{coveragePercent}%</span>
                      </div>
                      <Progress value={coveragePercent} className="h-2 md:h-3" />
                      <div className="text-xs text-muted-foreground mt-1">
                        Covers {solarProduction.toFixed(0)} of {monthlyUnits} units monthly
                      </div>
                    </div>

                    <div className="grid grid-cols-3 gap-2 md:gap-4 pt-3 md:pt-4 border-t border-primary/20">
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Production</div>
                        <div className="text-sm md:text-lg font-bold text-foreground">
                          {recommendedSystem.productionMin}-{recommendedSystem.productionMax}
                        </div>
                        <div className="text-xs text-muted-foreground">units/month</div>
                      </div>
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Independence</div>
                        <div className="text-sm md:text-lg font-bold text-accent">{energyIndependence}%</div>
                        <div className="text-xs text-muted-foreground">self-powered</div>
                      </div>
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Panels</div>
                        <div className="text-sm md:text-lg font-bold text-foreground">{recommendedSystem.panelCount}</div>
                        <div className="text-xs text-muted-foreground">high-efficiency</div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Financial Analysis Tabs */}
                <Tabs defaultValue="cost" className="w-full">
                  <TabsList className="grid w-full grid-cols-3 h-auto">
                    <TabsTrigger value="cost" className="text-xs md:text-sm py-2">Cost Breakdown</TabsTrigger>
                    <TabsTrigger value="savings" className="text-xs md:text-sm py-2">Savings</TabsTrigger>
                    <TabsTrigger value="environment" className="text-xs md:text-sm py-2">Environment</TabsTrigger>
                  </TabsList>
                  
                  <TabsContent value="cost" className="space-y-3 md:space-y-4 mt-4 md:mt-6">
                    <div className="space-y-2 md:space-y-3">
                      <div className="flex justify-between items-center p-3 md:p-4 bg-muted/50 rounded-lg">
                        <span className="text-xs md:text-sm font-medium text-muted-foreground">System Cost</span>
                        <span className="font-bold text-base md:text-lg text-foreground">₹{recommendedSystem.cost.toLocaleString('en-IN')}</span>
                      </div>
                      
                      <div className="flex justify-between items-center p-3 md:p-4 bg-accent/10 rounded-lg border border-accent/20">
                        <div className="flex items-center gap-2">
                          <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent" />
                          <span className="text-xs md:text-sm font-medium text-accent">Government Subsidy</span>
                        </div>
                        <span className="font-bold text-base md:text-lg text-accent">- ₹{recommendedSystem.subsidy.toLocaleString('en-IN')}</span>
                      </div>
                      
                      <div className="flex justify-between items-center p-4 md:p-5 bg-primary text-primary-foreground rounded-lg shadow-lg">
                        <span className="font-bold text-sm md:text-base">Your Final Investment</span>
                        <span className="font-black text-xl md:text-2xl">₹{systemCostAfterSubsidy.toLocaleString('en-IN')}</span>
                      </div>

                      <div className="grid grid-cols-2 gap-2 md:gap-3 pt-2">
                        <div className="p-2 md:p-3 bg-muted/30 rounded-lg text-center">
                          <div className="text-xs text-muted-foreground mb-1">Cost per kW</div>
                          <div className="text-sm md:text-lg font-bold">₹{Math.round(systemCostAfterSubsidy / recommendedSystem.capacity).toLocaleString('en-IN')}</div>
                        </div>
                        <div className="p-2 md:p-3 bg-muted/30 rounded-lg text-center">
                          <div className="text-xs text-muted-foreground mb-1">Cost per Panel</div>
                          <div className="text-sm md:text-lg font-bold">₹{Math.round(systemCostAfterSubsidy / recommendedSystem.panelCount).toLocaleString('en-IN')}</div>
                        </div>
                      </div>
                    </div>
                  </TabsContent>
                  
                  <TabsContent value="savings" className="space-y-3 md:space-y-4 mt-4 md:mt-6">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 md:gap-4">
                      <div className="p-4 md:p-5 bg-secondary/10 rounded-xl border-2 border-secondary/20">
                        <div className="flex items-center gap-2 mb-2">
                          <Calendar className="w-3 h-3 md:w-4 md:h-4 text-secondary" />
                          <div className="text-xs text-muted-foreground font-medium">MONTHLY SAVINGS</div>
                        </div>
                        <div className="text-2xl md:text-3xl font-black text-secondary mb-1">₹{monthlySavings.toLocaleString('en-IN')}</div>
                        <div className="text-xs md:text-sm text-muted-foreground">Every month for 25+ years</div>
                      </div>
                      
                      <div className="p-4 md:p-5 bg-accent/10 rounded-xl border-2 border-accent/20">
                        <div className="flex items-center gap-2 mb-2">
                          <TrendingDown className="w-3 h-3 md:w-4 md:h-4 text-accent" />
                          <div className="text-xs text-muted-foreground font-medium">ANNUAL SAVINGS</div>
                        </div>
                        <div className="text-2xl md:text-3xl font-black text-accent mb-1">₹{annualSavings.toLocaleString('en-IN')}</div>
                        <div className="text-xs md:text-sm text-muted-foreground">Per year guaranteed</div>
                      </div>
                    </div>

                    <div className="p-4 md:p-6 bg-gradient-to-br from-primary/10 to-accent/10 rounded-xl border-2 border-primary/20 space-y-3 md:space-y-4">
                      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                        <div>
                          <div className="text-xs md:text-sm text-muted-foreground font-medium mb-1">PAYBACK PERIOD</div>
                          <div className="text-3xl md:text-4xl font-black text-primary">{paybackYears} Years</div>
                          <div className="text-xs md:text-sm text-muted-foreground mt-1">≈ {paybackMonths} months</div>
                        </div>
                        <div className="text-left sm:text-right">
                          <div className="text-xs md:text-sm text-muted-foreground font-medium mb-1">25-YEAR ROI</div>
                          <div className="text-3xl md:text-4xl font-black text-accent">{roi}%</div>
                        </div>
                      </div>
                      
                      <div className="pt-3 md:pt-4 border-t border-primary/20">
                        <div className="text-xs md:text-sm text-muted-foreground mb-2">LIFETIME SAVINGS (25 Years)</div>
                        <div className="text-2xl md:text-3xl font-black text-foreground">₹{lifetimeSavings.toLocaleString('en-IN')}</div>
                        <div className="text-xs md:text-sm text-accent font-semibold mt-1">
                          Including 5% annual tariff increase
                        </div>
                      </div>
                    </div>

                    <div className="p-3 md:p-4 bg-muted/50 rounded-lg space-y-2">
                      <div className="flex justify-between items-center text-xs md:text-sm">
                        <span className="text-muted-foreground">Break-even point</span>
                        <span className="font-bold text-foreground">Year {paybackYears}</span>
                      </div>
                      <div className="flex justify-between items-center text-xs md:text-sm">
                        <span className="text-muted-foreground">Profit after 25 years</span>
                        <span className="font-bold text-accent">₹{(lifetimeSavings - recommendedSystem.cost).toLocaleString('en-IN')}</span>
                      </div>
                      <div className="flex justify-between items-center text-xs md:text-sm">
                        <span className="text-muted-foreground">System warranty</span>
                        <span className="font-bold text-primary">25 Years</span>
                      </div>
                    </div>
                  </TabsContent>
                  
                  <TabsContent value="environment" className="space-y-3 md:space-y-4 mt-4 md:mt-6">
                    <div className="p-4 md:p-6 bg-accent/10 rounded-xl border-2 border-accent/20 space-y-3 md:space-y-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 md:w-12 md:h-12 bg-accent rounded-full flex items-center justify-center shrink-0">
                          <Leaf className="w-5 h-5 md:w-6 md:h-6 text-accent-foreground" />
                        </div>
                        <div>
                          <div className="text-xs md:text-sm text-muted-foreground font-medium">YOUR ENVIRONMENTAL IMPACT</div>
                          <div className="text-base md:text-lg font-bold text-accent">Making a Real Difference</div>
                        </div>
                      </div>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 md:gap-4 pt-3 md:pt-4">
                        <div className="p-3 md:p-4 bg-background rounded-lg">
                          <div className="text-xs text-muted-foreground mb-2">ANNUAL CO₂ REDUCTION</div>
                          <div className="text-2xl md:text-3xl font-black text-accent">{annualCO2Saved.toFixed(1)}</div>
                          <div className="text-xs md:text-sm text-muted-foreground">tons per year</div>
                        </div>
                        
                        <div className="p-3 md:p-4 bg-background rounded-lg">
                          <div className="text-xs text-muted-foreground mb-2">25-YEAR CO₂ SAVED</div>
                          <div className="text-2xl md:text-3xl font-black text-accent">{lifetimeCO2Saved.toFixed(0)}</div>
                          <div className="text-xs md:text-sm text-muted-foreground">tons total</div>
                        </div>
                      </div>

                      <div className="p-4 md:p-5 bg-gradient-to-br from-accent/20 to-accent/5 rounded-lg border border-accent/30">
                        <div className="flex items-center gap-3 mb-3">
                          <div className="text-3xl md:text-4xl">🌳</div>
                          <div>
                            <div className="text-xs md:text-sm text-muted-foreground">EQUIVALENT TO PLANTING</div>
                            <div className="text-2xl md:text-3xl font-black text-accent">{treesEquivalent}</div>
                            <div className="text-xs md:text-sm text-muted-foreground">trees over 25 years</div>
                          </div>
                        </div>
                      </div>

                      <div className="space-y-2 pt-2">
                        <div className="flex items-center gap-2 text-xs md:text-sm">
                          <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent shrink-0" />
                          <span className="text-muted-foreground">Reduces air pollution in Jaipur</span>
                        </div>
                        <div className="flex items-center gap-2 text-xs md:text-sm">
                          <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent shrink-0" />
                          <span className="text-muted-foreground">Decreases dependence on fossil fuels</span>
                        </div>
                        <div className="flex items-center gap-2 text-xs md:text-sm">
                          <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent shrink-0" />
                          <span className="text-muted-foreground">Contributes to India's climate goals</span>
                        </div>
                      </div>
                    </div>
                  </TabsContent>
                </Tabs>

                {/* CTA Buttons */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 md:gap-4 pt-3 md:pt-4">
                  <Button 
                    className="h-11 md:h-12 text-sm md:text-base font-bold" 
                    onClick={() => setShowDetails(!showDetails)}
                    variant="outline"
                  >
                    {showDetails ? 'Hide' : 'Compare'} All Systems
                  </Button>
                  
                  <Button className="h-11 md:h-12 text-sm md:text-base font-bold" variant="default" asChild>
                    <a href="/contact">Get Free Consultation</a>
                  </Button>
                </div>

                {/* All Systems Comparison */}
                {showDetails && (
                  <div className="space-y-3 md:space-y-4 pt-4 md:pt-6 border-t-2">
                    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
                      <h4 className="font-bold text-lg md:text-xl">Compare All Solar Systems</h4>
                      <span className="text-xs md:text-sm text-muted-foreground">{solarSystems.length} options available</span>
                    </div>
                    <div className="grid grid-cols-1 gap-3 md:gap-4">
                      {solarSystems.map((system, index) => {
                        const isRecommended = system.capacity === recommendedSystem.capacity;
                        const systemAvgProduction = (system.productionMin + system.productionMax) / 2;
                        const systemCoverage = Math.min(100, Math.round((systemAvgProduction / monthlyUnits) * 100));
                        
                        return (
                          <div 
                            key={index}
                            className={`p-4 md:p-5 rounded-xl border-2 transition-all cursor-pointer hover:shadow-lg ${
                              isRecommended
                                ? 'border-primary bg-primary/5 shadow-md' 
                                : 'border-border hover:border-primary/50 bg-background'
                            }`}
                            onClick={() => setMonthlyUnits(Math.round(systemAvgProduction))}
                          >
                            <div className="flex flex-col sm:flex-row justify-between items-start gap-3 mb-3 md:mb-4">
                              <div className="flex-1">
                                <div className="flex flex-wrap items-center gap-2 md:gap-3 mb-2">
                                  <div className="text-xl md:text-2xl font-black text-foreground">{system.capacity} kW</div>
                                  {isRecommended && (
                                    <span className="px-2 md:px-3 py-1 bg-primary text-primary-foreground text-xs font-bold rounded-full flex items-center gap-1">
                                      <CheckCircle2 className="w-3 h-3" />
                                      BEST MATCH
                                    </span>
                                  )}
                                </div>
                                <div className="text-xs md:text-sm text-muted-foreground mb-2 md:mb-3">
                                  {system.panelCount} panels • {system.productionMin}-{system.productionMax} units/month
                                </div>
                                <div className="flex items-center gap-2 mb-2">
                                  <Progress value={systemCoverage} className="h-1.5 md:h-2 flex-1" />
                                  <span className="text-xs md:text-sm font-bold text-accent min-w-[40px] md:min-w-[45px]">{systemCoverage}%</span>
                                </div>
                              </div>
                            </div>
                            
                            <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 md:gap-3 text-xs md:text-sm">
                              <div className="p-2 md:p-3 bg-muted/50 rounded-lg">
                                <div className="text-xs text-muted-foreground mb-1">System Cost</div>
                                <div className="font-bold text-foreground">₹{(system.cost / 1000).toFixed(0)}K</div>
                              </div>
                              <div className="p-2 md:p-3 bg-accent/10 rounded-lg">
                                <div className="text-xs text-muted-foreground mb-1">Subsidy</div>
                                <div className="font-bold text-accent">₹{(system.subsidy / 1000).toFixed(0)}K</div>
                              </div>
                              <div className="p-2 md:p-3 bg-primary/10 rounded-lg">
                                <div className="text-xs text-muted-foreground mb-1">Final Cost</div>
                                <div className="font-bold text-primary">₹{((system.cost - system.subsidy) / 1000).toFixed(0)}K</div>
                              </div>
                              <div className="p-2 md:p-3 bg-secondary/10 rounded-lg">
                                <div className="text-xs text-muted-foreground mb-1">Area Needed</div>
                                <div className="font-bold text-secondary">{system.capacity * 100} sqft</div>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                    
                    <div className="p-3 md:p-4 bg-muted/30 rounded-lg">
                      <p className="text-xs md:text-sm text-muted-foreground text-center">
                        💡 <strong>Tip:</strong> Click on any system to see how it would work for your consumption
                      </p>
                    </div>
                  </div>
                )}

                {/* Calculator Info */}
                <div className="p-4 md:p-5 bg-gradient-to-br from-muted/50 to-muted/20 rounded-xl border space-y-3">
                  <div className="flex items-center gap-2 mb-2">
                    <Info className="w-4 h-4 md:w-5 md:h-5 text-primary shrink-0" />
                    <h5 className="font-bold text-sm md:text-base">How This Calculator Works</h5>
                  </div>
                  <div className="space-y-2 text-xs md:text-sm text-muted-foreground leading-relaxed">
                    <div className="flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent mt-0.5 shrink-0" />
                      <p><strong className="text-foreground">Smart Recommendations:</strong> We analyze your consumption and recommend a system that covers 85% of your needs for optimal savings.</p>
                    </div>
                    <div className="flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent mt-0.5 shrink-0" />
                      <p><strong className="text-foreground">Complete Package:</strong> Prices include solar panels, inverter, mounting structure, installation, net metering setup, and 25-year warranty.</p>
                    </div>
                    <div className="flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent mt-0.5 shrink-0" />
                      <p><strong className="text-foreground">Government Benefits:</strong> Subsidy amounts are based on current PM Surya Ghar Yojana rates for Rajasthan.</p>
                    </div>
                    <div className="flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 md:w-4 md:h-4 text-accent mt-0.5 shrink-0" />
                      <p><strong className="text-foreground">Realistic Projections:</strong> Savings calculations include 5% annual electricity tariff increase for accurate long-term estimates.</p>
                    </div>
                  </div>
                </div>

                <div className="pt-2">
                  <p className="text-xs text-center text-muted-foreground px-2">
                    <strong>Note:</strong> Final pricing may vary based on roof type, location accessibility, and specific site requirements. Get a free site inspection for exact quote.
                  </p>
                </div>
              </CardContent>
            </Card>
          </section>

          {/* Quick Benefits */}
          <section className="space-y-6">
            <h3 className="text-2xl font-bold">Why Choose Solar?</h3>
            <div className="space-y-4">
              <div className="flex gap-4 items-start p-4 bg-background rounded-xl border-2 border-primary/20 hover:border-primary transition-all">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center shrink-0">
                  <IndianRupee className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <h4 className="font-bold text-lg mb-1">Save Money</h4>
                  <p className="text-sm text-muted-foreground">Reduce electricity bills by up to 90% and protect against rising tariffs</p>
                </div>
              </div>

              <div className="flex gap-4 items-start p-4 bg-background rounded-xl border-2 border-accent/20 hover:border-accent transition-all">
                <div className="w-12 h-12 bg-accent/10 rounded-lg flex items-center justify-center shrink-0">
                  <Sun className="w-6 h-6 text-accent" />
                </div>
                <div>
                  <h4 className="font-bold text-lg mb-1">Clean Energy</h4>
                  <p className="text-sm text-muted-foreground">Generate pollution-free electricity and reduce your carbon footprint</p>
                </div>
              </div>

              <div className="flex gap-4 items-start p-4 bg-background rounded-xl border-2 border-secondary/20 hover:border-secondary transition-all">
                <div className="w-12 h-12 bg-secondary/10 rounded-lg flex items-center justify-center shrink-0">
                  <Zap className="w-6 h-6 text-secondary" />
                </div>
                <div>
                  <h4 className="font-bold text-lg mb-1">Energy Independence</h4>
                  <p className="text-sm text-muted-foreground">Generate your own power and reduce grid dependency</p>
                </div>
              </div>

              <div className="p-6 bg-primary text-primary-foreground rounded-xl text-center space-y-3">
                <div className="text-4xl font-black">25 Years</div>
                <div className="text-sm">Performance Warranty on All Systems</div>
              </div>
            </div>
          </section>

          {/* FAQ Section */}
          <section className="space-y-8">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tight">Frequently Asked Questions</h2>
              <p className="text-muted-foreground">
                Common questions about solar installation in Jaipur.
              </p>
            </div>

            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, i) => (
                <AccordionItem key={i} value={`item-${i}`} className="border-b-muted bg-background mb-4 rounded-lg px-6 shadow-sm border">
                  <AccordionTrigger className="hover:no-underline font-bold text-left py-4">
                    {faq.q}
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground leading-relaxed pb-6">
                    {faq.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>

            <div className="bg-foreground text-background p-8 rounded-2xl space-y-4">
              <h4 className="font-bold text-xl">Still have questions?</h4>
              <p className="text-background/70">Our experts are here to help you understand every aspect of solar energy.</p>
              <Button variant="secondary" asChild>
                <a href="/contact">Contact Support</a>
              </Button>
            </div>
          </section>

        </div>

        {/* Educational Image Section */}
        <section className="mt-24 space-y-12">
          <div className="text-center space-y-4">
            <h2 className="text-3xl md:text-4xl font-bold">Understanding Solar Technology</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Learn about the components and technology that power your solar energy system
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <Card className="overflow-hidden border-2 hover:border-primary transition-all hover:shadow-xl">
              <div className="aspect-video overflow-hidden">
                <img 
                  src="https://miaoda-site-img.s3cdn.medo.dev/images/KLing_26483c92-d67f-4c65-b3fc-2787774b6f8e.jpg" 
                  alt="Solar panel technology close-up" 
                  className="w-full h-full object-cover hover:scale-110 transition-transform duration-500"
                />
              </div>
              <CardHeader>
                <CardTitle className="text-xl">Solar Panels</CardTitle>
                <CardDescription>
                  High-efficiency photovoltaic cells that convert sunlight into electricity with industry-leading performance
                </CardDescription>
              </CardHeader>
            </Card>

            <Card className="overflow-hidden border-2 hover:border-primary transition-all hover:shadow-xl">
              <div className="aspect-video overflow-hidden">
                <img 
                  src="https://miaoda-site-img.s3cdn.medo.dev/images/KLing_2f9bb524-6239-4331-b2dc-e709c30f5df4.jpg" 
                  alt="Solar inverter and battery system" 
                  className="w-full h-full object-cover hover:scale-110 transition-transform duration-500"
                />
              </div>
              <CardHeader>
                <CardTitle className="text-xl">Inverter & Storage</CardTitle>
                <CardDescription>
                  Advanced inverters and battery systems that ensure reliable power supply even during grid outages
                </CardDescription>
              </CardHeader>
            </Card>

            <Card className="overflow-hidden border-2 hover:border-primary transition-all hover:shadow-xl">
              <div className="aspect-video overflow-hidden">
                <img 
                  src="https://miaoda-site-img.s3cdn.medo.dev/images/KLing_0942bf49-76f5-4650-8826-0bdb8c5887b3.jpg" 
                  alt="Solar monitoring system dashboard" 
                  className="w-full h-full object-cover hover:scale-110 transition-transform duration-500"
                />
              </div>
              <CardHeader>
                <CardTitle className="text-xl">Monitoring System</CardTitle>
                <CardDescription>
                  Real-time monitoring and analytics to track your system's performance and energy production
                </CardDescription>
              </CardHeader>
            </Card>
          </div>
        </section>

      </div>
    </div>
  );
};

export default Resources;